inherit_from: .rubocop_todo.yml

AllCops:
    NewCops: enable

Lint/MissingSuper:
    Enabled: False

Layout/LineLength:
    Max: 125
    Exclude:
        - "spec/**/*"
        - "test/**/*"

Metrics/AbcSize:
    Max: 25

Metrics/BlockLength:
    Max: 20
    Exclude:
        - "spec/**/*"
        - "*.gemspec"

Metrics/MethodLength:
    Max: 20

Style/Documentation:
    Exclude:
        - "spec/**/*"
        - "test/**/*"

Gemspec/DevelopmentDependencies:
    EnforcedStyle: gemspec

Naming/FileName:
    Exclude:
        - "lib/jekyll-timeline.rb" # spec helper gets confused otherwise
